language: java

jdk:
  - openjdk8
  
branches:
  only:
  - main
  - development
  - development2

before_install: 
  - sudo apt update

install:
  - sudo apt install maven -y

script:
  - mvn clean
  - mvn package jacoco:report

after_script:
  - cd SourceCodeAnalyzer
  - java -jar target/SourceCodeAnalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar
  - diff output_metrics.csv src/main/resources/manual_metrics.csv || exit 1

after_success:
  - echo "Everything went well"
