language: java

jdk:
  - openjdk8
  
branches:
  only:
  - master
  - development

before_install: 
  - sudo apt update

install:
  - sudo apt install maven -y

script:
  - mvn clean
  - mvn package jacoco:report
